const fs = require('fs');

const raw = fs.readFileSync('public/data/fauna_flora.json', 'utf8');
const data = JSON.parse(raw);

// 1. Quaternary / Pleistocene Megafauna (including all 16 from mundoprehistorico.com/extintos-naturales/)
const quaternarySpecies = [
  {
    id: "glyptodon",
    name: "Glyptodon clavipes",
    commonName: "Gliptodonte",
    image: "assets/species/glyptodon.jpg",
    group: "Mamífero acorazado (Cingulado gliptodóntido)",
    diet: "Herbívoro (Gramíneas duras y vegetación palustre)",
    habitat: "Terrestre (Pampas, estepas y sabanas abiertas de Sudamérica)",
    length: "3.3 m",
    weight: "2.0 toneladas",
    scaleVsHuman: "Del tamaño y peso de un automóvil utilitario compacto (Volkswagen Escarabajo).",
    description: "Colosal mamífero emparentado con los armadillos, protegido por un caparazón rígido de más de 1,000 osteodermos óseos hexagonales de hasta 2.5 cm de grosor. Su cola acorazada con anillos óseos funcionaba como un bate defensivo frente a depredadores. Convivió con los primeros grupos humanos en las pampas sudamericanas.",
    lat: -34.60,
    lon: -58.38,
    fossilSite: "Formación Luján, Pampas Argentinas (Sudamérica)"
  },
  {
    id: "smilodon",
    name: "Smilodon populator",
    commonName: "Tigre Dientes de Sable",
    image: "assets/species/smilodon_mundo.jpg",
    group: "Mamífero carnívoro (Félido macairodontino)",
    diet: "Carnívoro (Superdepredador de megaherbívoros)",
    habitat: "Terrestre (Llanuras, bosques abiertos y matorrales americanos)",
    length: "2.6 m",
    weight: "400 kg",
    scaleVsHuman: "Mucho más robusto y masivo que un león o tigre moderno, hombros hipertrofiados.",
    description: "El mayor felino dientes de sable de la historia del planeta. Poseía colmillos curvados aserrados de hasta 28 cm con los que infligía mordiscos degolladores de extrema precisión tras inmovilizar a sus presas con unas patas delanteras descomunales.",
    lat: -31.42,
    lon: -64.18,
    fossilSite: "Cueva de Lagoa Santa (Brasil) y Rancho La Brea (EE. UU.)"
  },
  {
    id: "mammuthus",
    name: "Mammuthus primigenius",
    commonName: "Mamut Lanudo",
    image: "assets/species/mamut_mundo.jpg",
    group: "Mamífero proboscídeo (Elefántidos)",
    diet: "Herbívoro (Gramíneas, juncos y musgos de la estepa)",
    habitat: "Terrestre (Estepa de mamuts periglacial euroasiática y beringiana)",
    length: "3.8 m",
    weight: "6.0 toneladas",
    scaleVsHuman: "Más de 3.4 m a la cruz, duplicando la altura de un ser humano.",
    description: "El icono de las Edades de Hielo. Equipado con un abrigo de doble capa de pelo de hasta 90 cm, colmillos en espiral de hasta 4.2 metros para retirar la nieve invernal y una joroba adiposa de reserva energética en la espalda. Abundantemente retratado en el arte parietal paleolítico.",
    lat: 67.50,
    lon: 133.40,
    fossilSite: "Permafrost del Río Lena y Siberia Oriental (Rusia)"
  },
  {
    id: "megatherium",
    name: "Megatherium americanum",
    commonName: "Megaterio (Perezoso Terrestre Gigante)",
    image: "assets/species/megaterio.jpg",
    group: "Mamífero xenartro (Folívoro megatérido)",
    diet: "Herbívoro ramoneador (Hojas tiernas, brotes de copa y raíces)",
    habitat: "Terrestre (Bosques templados, matorrales y pampas sudamericanas)",
    length: "6.0 m",
    weight: "4.0 toneladas",
    scaleVsHuman: "Al erguirse sobre dos patas alcanzaba más de 4 metros de altura, rivalizando con los mayores proboscídeos.",
    description: "Titánico perezoso terrestre cuadrúpedo y facultativamente bípedo. Poseía una sólida pelvis y una cola musculosa que formaban un trípode para erguirse a ramonear ramas altas, armado con formidables garras curvadas de 30 cm con las que repelía a depredadores como Smilodon.",
    lat: -38.52,
    lon: -60.25,
    fossilSite: "Barrancas del Río Quequén Grande (Buenos Aires, Argentina)"
  },
  {
    id: "macrauchenia",
    name: "Macrauchenia patachonica",
    commonName: "Macrauquenia",
    image: "assets/species/macrauchenia.jpg",
    group: "Mamífero litopterno (Litopterna)",
    diet: "Herbívoro (Hojas, hierbas y vegetación arbustiva)",
    habitat: "Terrestre (Llanuras aluviales y estepas patagónicas de Sudamérica)",
    length: "3.0 m",
    weight: "1,000 kg",
    scaleVsHuman: "Aproximadamente 2 metros de altura al lomo, complexión comparable a un gran camello.",
    description: "Enigmático ungulado sudamericano descubierto por Charles Darwin. Con extremidades largas adaptadas a cambios rápidos de dirección para escapar de depredadores, fosas nasales en la parte superior del cráneo que sugieren una corta trompa prehensil o labio muscular extensible, y tres dedos en cada pata.",
    lat: -50.12,
    lon: -69.80,
    fossilSite: "Puerto San Julián, Santa Cruz (Patagonia, Argentina)"
  },
  {
    id: "toxodon",
    name: "Toxodon platensis",
    commonName: "Toxodonte",
    image: "assets/species/toxodon.jpg",
    group: "Mamífero notoungulado (Toxodóntido)",
    diet: "Herbívoro mixto (Pastos duros y vegetación ripícola)",
    habitat: "Terrestre / Semiacuático (Humedales, orillas de ríos y sabanas sudamericanas)",
    length: "2.7 m",
    weight: "1,500 kg",
    scaleVsHuman: "Morfología y masa semejante a la de un rinoceronte sin cuernos o hipopótamo común.",
    description: "Uno de los últimos y más exitosos representantes de los notoungulados, un linaje autóctono sudamericano de ungulados. Sus incisivos curvados y de crecimiento continuo en forma de arco (de ahí su nombre 'diente en arco') le permitían cortar vegetación abrasiva con un alto contenido de sílice.",
    lat: -31.73,
    lon: -60.53,
    fossilSite: "Formación Arroyo Feliciano, Entre Ríos (Argentina)"
  },
  {
    id: "mastodonte_americano",
    name: "Mammut americanum",
    commonName: "Mastodonte Americano",
    image: "assets/species/mastodonte_americano.jpg",
    group: "Mamífero proboscídeo (Mamútidos)",
    diet: "Herbívoro ramoneador (Ramas de abetos, coníferas y vegetación de humedal)",
    habitat: "Terrestre (Bosques boreales de coníferas y turberas de Norteamérica)",
    length: "4.5 m",
    weight: "5.5 toneladas",
    scaleVsHuman: "Algo más bajo pero mucho más ancho y fornido que los mamuts contemporáneos.",
    description: "Proboscídeo de ramas evolutivas distintas a los verdaderos elefantes. Se caracterizaba por sus molares con cúspides cónicas pronunciadas (bunodontos) diseñados para desmenuzar ramas leñosas, un pelaje áspero castaño y defensas alargadas ligeramente divergentes.",
    lat: 39.82,
    lon: -84.90,
    fossilSite: "Big Bone Lick State Park, Kentucky (EE. UU.)"
  },
  {
    id: "lobo_gigante",
    name: "Aenocyon dirus",
    commonName: "Lobo Terrible / Lobo Gigante",
    image: "assets/species/lobo_gigante.jpg",
    group: "Mamífero carnívoro (Cánido hiperdepredador)",
    diet: "Carnívoro (Cazador en jauría y carroñero facultativo)",
    habitat: "Terrestre (Pastizales, bosques y llanuras abiertas de América)",
    length: "1.8 m",
    weight: "85 kg",
    scaleVsHuman: "25% más macizo que un lobo gris moderno, con cráneo ancho y dientes trituradores de hueso.",
    description: "El cánido más famoso del Pleistoceno, popularizado por los miles de esqueletos hallados en los pozos de brea de La Brea. Poseía una mordida devastadora capaz de fracturar huesos mayores para consumir médula ósea, compitiendo directamente con Smilodon por los grandes herbívoros.",
    lat: 34.06,
    lon: -118.36,
    fossilSite: "Pozos de alquitrán de Rancho La Brea, Los Ángeles (California, EE. UU.)"
  },
  {
    id: "oso_cavernario",
    name: "Ursus spelaeus",
    commonName: "Oso de las Cavernas",
    image: "assets/species/oso_cavernario.jpg",
    group: "Mamífero carnívoro (Úrsido)",
    diet: "Mayormente herbívoro especializado / Omnívoro estacional",
    habitat: "Terrestre (Valles alpinos, bosques templados y cuevas kársticas de Europa)",
    length: "3.5 m erguido",
    weight: "800 kg",
    scaleVsHuman: "Notable frente abultada, hasta 1.35 m a la cruz y más de 3 metros al ponerse de pie.",
    description: "Colosal úrsido del Pleistoceno europeo con una frente empinada característica. Pasaba los duros inviernos glaciares hibernando en profundas cuevas kársticas, donde morían miles de individuos ancianos o débiles, dejando ingentes acumulaciones de esqueletos que asombraron a los primeros naturalistas.",
    lat: 44.38,
    lon: 4.41,
    fossilSite: "Cueva de Chauvet-Pont d'Arc (Ardèche, Francia)"
  },
  {
    id: "leon_cavernas",
    name: "Panthera spelaea",
    commonName: "León de las Cavernas Euroasiático",
    image: "assets/species/leon_cavernas.jpg",
    group: "Mamífero carnívoro (Félido panterino)",
    diet: "Carnívoro superdepredador (Renos, bisontes esteparios y crías de proboscídeos)",
    habitat: "Terrestre (Estepas frías, tundra periglacial y bosques de Eurasia)",
    length: "2.5 m (sin cola)",
    weight: "340 kg",
    scaleVsHuman: "Entre un 15% y 25% más voluminoso que los leones subsaharianos actuales.",
    description: "El mayor gran felino del hemisferio norte durante el Cuaternario. Los recientes hallazgos de cachorros congelados en el permafrost siberiano han revelado su pelaje pardo amarillento denso adaptado al clima gélido y la carencia de melena abundante en los machos, corroborando fielmente las pinturas rupestres paleolíticas.",
    lat: 67.45,
    lon: 138.80,
    fossilSite: "Cuenca del Río Uyandina y Cueva Denisova (Siberia, Rusia)"
  },
  {
    id: "rinoceronte_lanudo",
    name: "Coelodonta antiquitatis",
    commonName: "Rinoceronte Lanudo",
    image: "assets/species/rinoceronte_lanudo.jpg",
    group: "Mamífero perisodáctilo (Rinocerótidos)",
    diet: "Herbívoro (Gramíneas, líquenes, musgos y arbustos enanos de tundra)",
    habitat: "Terrestre (Estepa fría euroasiática desde las Islas Británicas hasta el Extremo Oriente)",
    length: "3.7 m",
    weight: "2.5 toneladas",
    scaleVsHuman: "Casi 2 metros de altura al hombro, con un colosal cuerno frontal curvado.",
    description: "Pariente acorazado por un espeso vellón de pelo lanoso de dos capas y grasa subcutánea. Ostentaba un cuerno anterior de queratina aplanado lateralmente de más de 1.3 metros con el que apartaba la densa capa de nieve para alcanzar el pasto bajo el suelo helado.",
    lat: 49.84,
    lon: 24.03,
    fossilSite: "Minas de ozokerita de Starunia (Ucrania) y Yana RHS (Siberia)"
  },
  {
    id: "megalocero",
    name: "Megaloceros giganteus",
    commonName: "Megalocero (Ciervo Gigante / Alce Irlandés)",
    image: "assets/species/megalocero.jpg",
    group: "Mamífero artiodáctilo (Cérvidos)",
    diet: "Herbívoro (Gramíneas ricas en calcio y fósforo de praderas abiertas)",
    habitat: "Terrestre (Llanuras y estepas arbustivas templadas de Europa y Asia)",
    length: "3.2 m",
    weight: "700 kg",
    scaleVsHuman: "2.1 metros de altura a la cruz, con astas que superaban holgadamente la envergadura de cualquier vehículo.",
    description: "Poseedor de la cornamenta más monumental de la historia evolutiva: hasta 3.65 metros de punta a punta y 40 kg de masa ósea neta que los machos regeneraban anualmente. La demanda extrema de minerales para mineralizar semejante estructura ósea pudo acelerar su extinción al cambiar la vegetación postglaciar.",
    lat: 53.25,
    lon: -6.20,
    fossilSite: "Turberas de Ballybetagh Bog (Dublín, Irlanda)"
  },
  {
    id: "diprotodon",
    name: "Diprotodon optatum",
    commonName: "Diprotodonte (Vómbat Gigante)",
    image: "assets/species/diprotodon.jpg",
    group: "Mamífero marsupial (Diprotodóntidos)",
    diet: "Herbívoro (Arbustos salinos, hojas de eucalipto y pastos semiáridos)",
    habitat: "Terrestre (Sabanas abiertas, matorrales y bosques de Australia)",
    length: "3.8 m",
    weight: "2.8 toneladas",
    scaleVsHuman: "El mayor marsupial de todos los tiempos: del tamaño y corpulencia de un rinoceronte blanco.",
    description: "El gigante indiscutible de la megafauna australiana. Este marsupial dotado de una bolsa marsupial orientada hacia atrás poseía enormes incisivos en forma de cincel y patas digitígradas que le permitían recorrer cientos de kilómetros en busca de fuentes de agua durante los ciclos de sequía continental.",
    lat: -31.80,
    lon: 136.50,
    fossilSite: "Yacimiento lacustre del Lago Callabonna (Australia Meridional)"
  },
  {
    id: "procoptodon",
    name: "Procoptodon goliah",
    commonName: "Procoptodonte (Canguro Gigante de Cara Corta)",
    image: "assets/species/procoptodon.jpg",
    group: "Mamífero marsupial (Macropódido estenurino)",
    diet: "Herbívoro ramoneador (Hojas duras de acacias y arbustos esclerófilos)",
    habitat: "Terrestre (Llanuras semiáridas y sabanas arbustivas de Australia central y oriental)",
    length: "2.7 m erguido",
    weight: "240 kg",
    scaleVsHuman: "Casi el triple del peso de un canguro rojo actual, con un rostro simiesco chato.",
    description: "El canguro más descomunal que haya existido. A diferencia de los canguros modernos que saltan, la anatomía articular de sus caderas y su pata rematada en un único dedo ungulado modificado indican que se desplazaba caminando a grandes zancadas bípedas, alzando sus brazos prensiles para deshojar ramas altas.",
    lat: -32.50,
    lon: 142.30,
    fossilSite: "Lagos Menindee y Cueva de Naracoorte (Nueva Gales del Sur, Australia)"
  },
  {
    id: "megalania",
    name: "Varanus priscus",
    commonName: "Megalania (Lagarto Gigante Australiano)",
    image: "assets/species/megalania.jpg",
    group: "Reptil escamoso (Varánidos gigantes)",
    diet: "Carnívoro superdepredador y carroñero de megafauna",
    habitat: "Terrestre (Llanuras aluviales, matorrales y bosques australianos)",
    length: "6.5 m",
    weight: "800 kg",
    scaleVsHuman: "Más del doble de largo y hasta 10 veces más pesado que el Dragón de Komodo actual.",
    description: "El lagarto terrestre más gigantesco conocido por la ciencia. Equipado con dientes aserrados recurvados hacia atrás y posiblemente glándulas de veneno anticoagulante, acechaba a los grandes marsupiales como Diprotodon en emboscadas cerca de puntos de agua dulce en la Australia pleistocénica.",
    lat: -27.50,
    lon: 148.00,
    fossilSite: "Depósitos aluviales de Darling Downs, Queensland (Australia)"
  }
];

// Replace period 0 species
data.periods[0].species = quaternarySpecies;

// 2. Miocene 20 Ma: Add Titanis alongside Megalodon
const mioceneSpecies = [
  {
    id: "megalodon",
    name: "Otodus megalodon",
    commonName: "Megalodón (Tiburón Megadentado)",
    image: "assets/species/megalodon.jpg",
    group: "Condrictio carnívoro (Otodóntidos)",
    diet: "Carnívoro (Superdepredador marino de cetáceos)",
    habitat: "Marino costero y pelágico global en aguas cálidas y templadas",
    length: "18.0 m",
    weight: "50 toneladas",
    scaleVsHuman: "Su boca abierta de más de 2 metros permitía que un humano adulto se pusiera de pie en su interior.",
    description: "El mayor tiburón depredador de la historia geológica. Sus mandíbulas armadas con más de 250 dientes triangulares aserrados de hasta 18 cm generaban la mayor fuerza de mordida estimada en el reino animal (~180,000 N), capaz de aplastar las costillas de ballenas barbadas.",
    lat: 31.95,
    lon: -80.95,
    fossilSite: "Formación Yorktown y Sharktooth Hill (EE. UU. / Cuenca Pacífica)"
  },
  {
    id: "titanis",
    name: "Titanis walleri",
    commonName: "Titánis (Ave del Terror Gigante)",
    image: "assets/species/titanis.jpg",
    group: "Ave fororrácida carnívora (Phorusrhacidae)",
    diet: "Carnívoro veloz (Cazador activo de mamíferos ungulados medianos)",
    habitat: "Terrestre (Sabanas, pastizales y bosques abiertos subtropicales de Norteamérica)",
    length: "2.5 m de altura",
    weight: "150 kg",
    scaleVsHuman: "Su cabeza armada con un pico ganchudo macizo superaba la altura de un caballo.",
    description: "La única especie de las temibles 'aves del terror' fororrácidas sudamericanas que logró cruzar exitosamente hacia Norteamérica durante el Gran Intercambio Biótico Americano. Cazador corredor excepcionalmente veloz que utilizaba su hacha craneal para noquear presas.",
    lat: 29.65,
    lon: -82.60,
    fossilSite: "Yacimientos fósiles del Río Santa Fe (Florida, EE. UU.)"
  },
  {
    id: "paraceratherium",
    name: "Paraceratherium transouralicum",
    commonName: "Paraceraterio (Indricoterio)",
    image: "assets/species/paraceratherium.svg",
    group: "Mamífero perisodáctilo (Hiracodóntidos)",
    diet: "Herbívoro ramoneador (Hojas de copa alta)",
    habitat: "Terrestre (Bosques de galería y llanuras de Eurasia central)",
    length: "7.4 m",
    weight: "15 toneladas",
    scaleVsHuman: "Casi 5 metros de altura al hombro; miraba por encima del segundo piso de un edificio.",
    description: "Uno de los mayores mamíferos terrestres que jamás hayan caminado sobre el planeta, un rinoceronte sin cuernos de cuello elongado capaz de ramonear las copas de los árboles.",
    lat: 44.50,
    lon: 65.50,
    fossilSite: "Formación Chitarwata (Pakistán) y Kazajistán"
  },
  {
    id: "purussaurus",
    name: "Purussaurus brasiliensis",
    commonName: "Purussauro (Caimán Gigante del Amazonas)",
    image: "assets/species/purussaurus.svg",
    group: "Reptil crocodilio (Aligatórido)",
    diet: "Carnívoro superdepredador de aguas dulces",
    habitat: "Fluvial y lacustre (Sistema de humedales Pebas protoamazónico)",
    length: "12.5 m",
    weight: "8.4 toneladas",
    scaleVsHuman: "Cráneo colosal de 1.4 m de longitud, casi el doble de largo que el mayor cocodrilo marino moderno.",
    description: "Monstruoso caimán gigante que dominó las cálidas aguas tropicales del sistema Pebas miocénico, alimentándose de tortugas gigantes de caparazón duro, mamíferos notoungulados y peces de gran tamaño.",
    lat: -9.50,
    lon: -70.50,
    fossilSite: "Formación Solimões, Cuenca del Río Purus (Amazonia, Brasil/Perú)"
  }
];
data.periods[1].species = mioceneSpecies;

// 3. Cretaceous 66 Ma: Fix Tyrannosaurus (uncropped widescreen from Mundo Prehistorico) and add Triceratops, Ankylosaurus, Quetzalcoatlus, Mosasaurus, Velociraptor, Parasaurolophus
const cretaceous66Species = [
  {
    id: "tyrannosaurus",
    name: "Tyrannosaurus rex",
    commonName: "Tiranosaurio Rex",
    image: "assets/species/tyrannosaurus_mundo.jpg",
    group: "Dinosaurio terópodo (Tiranosáuridos)",
    diet: "Carnívoro (Superdepredador alfa y carroñero oportunista)",
    habitat: "Terrestre (Llanuras aluviales y bosques subtropicales de Laramidia)",
    length: "12.3 m",
    weight: "8.8 toneladas",
    scaleVsHuman: "3.7 metros de altura a la cadera, cráneo de 1.5 metros provisto de 60 dientes trituradores de hueso.",
    description: "El superdepredador indiscutible del Cretácico tardío en Norteamérica. Poseía la mayor fuerza de mordedura medida en animales terrestres (~57,000 N), visión binocular tridimensional estereoscópica superior a la de las aves de presa actuales y un fino sentido del olfato para detectar carroña a kilómetros de distancia.",
    lat: 47.50,
    lon: -106.50,
    fossilSite: "Formación Hell Creek, Montana (EE. UU.)"
  },
  {
    id: "triceratops",
    name: "Triceratops horridus",
    commonName: "Triceratops (Tres Cuernos)",
    image: "assets/species/triceratops.jpg",
    group: "Dinosaurio ornitisquio (Ceratópsidos)",
    diet: "Herbívoro (Palmas, cícadas y helechos de sotobosque)",
    habitat: "Terrestre (Bosques húmedos y valles fluviales de Norteamérica)",
    length: "9.0 m",
    weight: "9.0 toneladas",
    scaleVsHuman: "3 metros de altura, macizo como dos elefantes africanos, con una gola ósea impenetrable.",
    description: "El ceratópsido más colosal y reconocible. Ostentaba dos grandes cuernos supraorbitales de más de 1 metro de longitud y un cuerno nasal, respaldados por una sólida gola ósea posterior que protegía su cuello y servía para el cortejo y las batallas territoriales frente a rivales de su misma especie y ataques de T-Rex.",
    lat: 44.00,
    lon: -104.50,
    fossilSite: "Formación Lance, Wyoming (EE. UU.)"
  },
  {
    id: "ankylosaurus",
    name: "Ankylosaurus magniventris",
    commonName: "Anquilosaurio (Tanque Acorazado)",
    image: "assets/species/ankylosaurus.jpg",
    group: "Dinosaurio ornitisquio (Tireóforos anquilosáuridos)",
    diet: "Herbívoro bajo (Matorrales, raíces y tubérculos)",
    habitat: "Terrestre (Llanuras costeras y bosques de Norteamérica occidental)",
    length: "8.0 m",
    weight: "6.0 toneladas",
    scaleVsHuman: "Un tanque biológico bajo y acorazado con una porra caudal maciza capaz de quebrar huesos.",
    description: "El último y mayor de los anquilosáuridos. Su lomo estaba enteramente blindado por placas osteodérmicas y espinas óseas incrustadas en la piel, hasta en los párpados. Al final de su cola fusionada portaba una pesada maza ósea que blandía lateralmente con fuerza suficiente para fracturar las patas de un Tiranosaurio.",
    lat: 47.20,
    lon: -107.00,
    fossilSite: "Formación Hell Creek, Montana y Alberta (Canadá)"
  },
  {
    id: "velociraptor",
    name: "Velociraptor mongoliensis",
    commonName: "Velociraptor",
    image: "assets/species/velociraptor.jpg",
    group: "Dinosaurio terópodo (Dromeosáuridos emplumados)",
    diet: "Carnívoro ágil (Depredador activo de pequeños dinosaurios y reptiles)",
    habitat: "Terrestre (Dunas desérticas y oasis áridos de Asia Central)",
    length: "2.0 m",
    weight: "15 kg",
    scaleVsHuman: "Del tamaño de un pavo grande o lobo pequeño, cubierto de plumaje denso.",
    description: "Terópodo ágil dotado de plumas penáceas completas y una formidable garra en forma de hoz hipertrofiada en el segundo dedo de cada pie. El famoso fósil de los 'Dinosaurios Luchadores' demostró que empleaba sus garras para someter a presas como Protoceratops en combates a muerte en el desierto de Gobi.",
    lat: 44.15,
    lon: 103.20,
    fossilSite: "Acantilados Llameantes de Bayan Mandahu y Formación Djadochta (Desierto de Gobi, Mongolia)"
  },
  {
    id: "quetzalcoatlus",
    name: "Quetzalcoatlus northropi",
    commonName: "Quetzalcoatlus (Reptil Volador Gigante)",
    image: "assets/species/quetzalcoatlus.jpg",
    group: "Reptil volador (Pterosaurio azdárquido)",
    diet: "Carnívoro / Piscívoro (Depredador terrestre acechador y carroñero)",
    habitat: "Aéreo y terrestre (Llanuras de inundación interiores)",
    length: "11.0 m de envergadura alar",
    weight: "220 kg",
    scaleVsHuman: "Caminaba a cuatro patas erguido con la misma altura que una jirafa macho adulta (5.5 m).",
    description: "Uno de los mayores animales voladores de la historia terrestre. Con una envergadura equivalente a la de un avión Cessna y un pico desdentado puntiagudo de casi 2 metros, patrullaba el suelo a zancadas alimentándose de presas de tamaño medio que engullía enteras.",
    lat: 29.25,
    lon: -103.25,
    fossilSite: "Formación Javelina, Big Bend, Texas (EE. UU.)"
  },
  {
    id: "mosasaurus",
    name: "Mosasaurus hoffmannii",
    commonName: "Mosasaurio (Lagarto del Río Mosa)",
    image: "assets/species/mosasaurus.jpg",
    group: "Reptil marino escamoso (Mosasáuridos)",
    diet: "Carnívoro (Superdepredador marino de ammonites, tortugas y tiburones)",
    habitat: "Marino costero y de plataforma en mares epicontinentales cálidos",
    length: "17.0 m",
    weight: "14 toneladas",
    scaleVsHuman: "Casi el triple de largo que una orca marina, con aletas hidrodinámicas y cola bilobulada.",
    description: "Reptil escamoso marino emparentado con los varanos y serpientes. Poseía una doble fila de dientes en el paladar (dientes pterigoideos) que impedían que las presas resbalaran de su fauce, y una potente aleta caudal con la que propulsaba emboscadas letales a gran velocidad.",
    lat: 50.85,
    lon: 5.68,
    fossilSite: "Canteras de caliza de Maastricht (Río Mosa, Países Bajos)"
  },
  {
    id: "parasaurolophus",
    name: "Parasaurolophus walkeri",
    commonName: "Parasaurolofo (Pico de Pato de Cresta Tubular)",
    image: "assets/species/parasaurolophus.jpg",
    group: "Dinosaurio ornitisquio (Hadrosáuridos lambeosaurinos)",
    diet: "Herbívoro ramoneador (Acículas de pino, hojas y semillas duras)",
    habitat: "Terrestre (Bosques húmedos ribereños y deltas costeros de Laramidia)",
    length: "10.0 m",
    weight: "3.5 toneladas",
    scaleVsHuman: "Casi 4 metros de altura, con una espectacular cresta tubular curva de hasta 1.8 metros hacia atrás.",
    description: "Emblemático dinosaurio herbívoro 'pico de pato'. Su espectacular cresta craneal hueca albergaba conductos nasales complejos que funcionaban como una caja de resonancia acústica para emitir llamadas subsónicas de baja frecuencia a lo largo de kilómetros de bosque, además de servir como llamativo display visual.",
    lat: 50.70,
    lon: -111.50,
    fossilSite: "Parque Provincial del Dinosaurio, Formación Dinosaur Park, Alberta (Canadá)"
  }
];
data.periods[3].species = cretaceous66Species;

// 4. Cretaceous 105 Ma: Spinosaurus, Giganotosaurus, Iguanodon
const cretaceous105Species = [
  {
    id: "spinosaurus",
    name: "Spinosaurus aegyptiacus",
    commonName: "Espinosaurio (Lagarto de Espina)",
    image: "assets/species/spinosaurus_mundo.jpg",
    group: "Dinosaurio terópodo (Espinosáuridos semiacuáticos)",
    diet: "Piscívoro especializado y carnívoro de ribera (Peces celacantos gigantes y celurosaurios)",
    habitat: "Semiacuático (Sistemas de deltas fluviales y manglares del Sahara)",
    length: "15.0 m",
    weight: "7.5 toneladas",
    scaleVsHuman: "Más largo que Tyrannosaurus rex, con una vela dorsal de 1.8 m y cola en forma de aleta natatoria.",
    description: "El dinosaurio carnívoro más largo conocido. Altamente adaptado a la vida acuática en los sistemas fluviales del norte de África, con huesos densos para controlar la flotabilidad, una cola aplanada lateralmente como una aleta de tritón, hocico cónico similar al de un gavial y una monumental vela dorsal.",
    lat: 31.00,
    lon: 28.50,
    fossilSite: "Formación Bahariya (Egipto) y Lechos de Kem Kem (Marruecos)"
  },
  {
    id: "giganotosaurus",
    name: "Giganotosaurus carolinii",
    commonName: "Giganotosaurio (Lagarto Gigante del Sur)",
    image: "assets/species/giganotosaurus.jpg",
    group: "Dinosaurio terópodo (Carcharodontosáuridos)",
    diet: "Carnívoro superdepredador (Cazador de saurópodos titanosaurios)",
    habitat: "Terrestre (Llanuras de inundación y valles aluviales de la Patagonia)",
    length: "13.2 m",
    weight: "8.2 toneladas",
    scaleVsHuman: "Rivalizaba o superaba en tamaño a Tyrannosaurus rex, con dientes como dagas aserradas.",
    description: "Colosal terópodo carcharodontosáurido del Cretácico medio sudamericano. Dotado de mandíbulas armadas con dientes comprimidos lateralmente de hasta 15 cm aptos para desgarrar grandes masas de carne mediante ataques de corte rápido contra titanosaurios como Argentinosaurus.",
    lat: -39.20,
    lon: -68.80,
    fossilSite: "Formación Candeleros, Villa El Chocón, Neuquén (Patagonia, Argentina)"
  },
  {
    id: "iguanodon",
    name: "Iguanodon bernissartensis",
    commonName: "Iguanodonte (Diente de Iguana)",
    image: "assets/species/iguanodon.jpg",
    group: "Dinosaurio ornitisquio (Ornitópodos iguanodontianos)",
    diet: "Herbívoro (Helechos arborescentes, equisetos y coníferas)",
    habitat: "Terrestre (Llanuras aluviales y valles pantanosos europeos)",
    length: "10.0 m",
    weight: "4.5 toneladas",
    scaleVsHuman: "Capaz de marchar a cuatro o a dos patas, con un espolón defensivo cónico de 15 cm en el pulgar.",
    description: "Uno de los primeros dinosaurios nombrados en la historia de la ciencia. Sus manos exhibían pulgares modificados en afiladas púas cónicas que utilizaba tanto para defensa activa frente a terópodos como para manipular ramas duras.",
    lat: 50.48,
    lon: 3.65,
    fossilSite: "Mina de carbón de Bernissart (Bélgica) y Wealden (Reino Unido)"
  },
  {
    id: "argentinosaurus",
    name: "Argentinosaurus huinculensis",
    commonName: "Argentinosaurio (Titán de la Patagonia)",
    image: "assets/species/argentinosaurus.svg",
    group: "Dinosaurio saurópodo (Titanosaurios)",
    diet: "Herbívoro de gran altura (Coníferas gigantes y cícadas)",
    habitat: "Terrestre (Llanuras aluviales de Sudamérica)",
    length: "35.0 m",
    weight: "75 toneladas",
    scaleVsHuman: "Una sola de sus vértebras dorsales medía más de 1.6 metros de altura, rivalizando con la estatura humana.",
    description: "Considerado uno de los animales terrestres más pesados y masivos que jamás hayan existido sobre la Tierra, con vértebras reforzadas por articulaciones accesorias hiposfeno-hipantro para soportar un peso superior a 70 toneladas métricas.",
    lat: -38.90,
    lon: -69.20,
    fossilSite: "Formación Huincul, Plaza Huincul, Neuquén (Argentina)"
  }
];
data.periods[4].species = cretaceous105Species;

// 5. Jurassic 150 Ma: Allosaurus, Stegosaurus, Diplodocus, Brachiosaurus, Archaeopteryx, Kentrosaurus
const jurassic150Species = [
  {
    id: "allosaurus",
    name: "Allosaurus fragilis",
    commonName: "Alosaurio (Lagarto Extraño)",
    image: "assets/species/allosaurus.jpg",
    group: "Dinosaurio terópodo (Alosáuridos)",
    diet: "Carnívoro (Superdepredador jurásico de estegosáuridos y saurópodos)",
    habitat: "Terrestre (Llanuras semiáridas con bosques de galería de Norteamérica)",
    length: "9.5 m",
    weight: "2.3 toneladas",
    scaleVsHuman: "3 metros de altura a la cruz, con crestas lagrimales rojas sobre los ojos y brazos de tres garras.",
    description: "El león del Jurásico tardío. Con una apertura de mandíbula excepcionalmente amplia de más de 80 grados, utilizaba su maxilar superior a modo de hacha cortante para golpear y desangrar a grandes presas herbívoras.",
    lat: 39.30,
    lon: -110.80,
    fossilSite: "Cantera de Cleveland-Lloyd, Formación Morrison, Utah (EE. UU.)"
  },
  {
    id: "stegosaurus",
    name: "Stegosaurus stenops",
    commonName: "Estegosaurio (Lagarto con Tejado)",
    image: "assets/species/stegosaurus.jpg",
    group: "Dinosaurio ornitisquio (Estegosáuridos)",
    diet: "Herbívoro bajo (Musgos, helechos y cícadas)",
    habitat: "Terrestre (Llanuras aluviales jurásicas)",
    length: "9.0 m",
    weight: "5.0 toneladas",
    scaleVsHuman: "4 metros de altura hasta la cúspide de sus placas dorsales, con cola armada con púas óseas (thagomizer).",
    description: "Reconocible al instante por la doble fila alterna de 17 placas óseas triangulares a lo largo del lomo, utilizadas tanto para termorregulación vascular como para display visual, y cuatro púas defensivas de 60 cm en la punta de la cola (thagomizer) con las que hería mortalmente a Alosaurios.",
    lat: 40.40,
    lon: -108.50,
    fossilSite: "Monumento Nacional de los Dinosaurios, Formación Morrison, Colorado/Utah (EE. UU.)"
  },
  {
    id: "diplodocus",
    name: "Diplodocus carnegii",
    commonName: "Diplodoco (Doble Viga)",
    image: "assets/species/diplodocus.jpg",
    group: "Dinosaurio saurópodo (Diplodócidos)",
    diet: "Herbívoro ramoneador bajo y medio (Helechos y coníferas)",
    habitat: "Terrestre (Llanuras fluviales de Norteamérica)",
    length: "27.0 m",
    weight: "14 toneladas",
    scaleVsHuman: "Longitud de un autobús articulado doble; su cola en látigo superaba la velocidad del sonido al restallar.",
    description: "Saurópodo icónico de complexión esbelta pero extraordinaria longitud. Poseía una cola finísima compuesta por más de 80 vértebras que funcionaba como un látigo supersónico para disuadir depredadores y defender a la manada.",
    lat: 41.50,
    lon: -106.00,
    fossilSite: "Cantera Sheep Creek, Formación Morrison, Wyoming (EE. UU.)"
  },
  {
    id: "brachiosaurus",
    name: "Brachiosaurus altithorax",
    commonName: "Braquiosaurio (Lagarto con Brazos)",
    image: "assets/species/brachiosaurus.jpg",
    group: "Dinosaurio saurópodo (Braquiosáuridos)",
    diet: "Herbívoro de copa alta (Coníferas, ginkgos y cícadas arborescentes)",
    habitat: "Terrestre (Valles fluviales y bosques altos del Jurásico)",
    length: "23.0 m",
    weight: "35 toneladas",
    scaleVsHuman: "Más de 12 metros de altura total; alcanzaba la altura de un cuarto piso sin despegar las patas del suelo.",
    description: "Monumento viviente del Jurásico con extremidades anteriores más largas que las posteriores, lo que otorgaba a su lomo una postura inclinada hacia arriba semejante a la de una colosal jirafa, facilitándole el ramoneo directo en las copas de las coníferas.",
    lat: 39.05,
    lon: -108.70,
    fossilSite: "Grand River Valley, Formación Morrison, Colorado (EE. UU.)"
  },
  {
    id: "archaeopteryx",
    name: "Archaeopteryx lithographica",
    commonName: "Arqueópterix (Ala Antigua)",
    image: "assets/species/archaeopteryx.jpg",
    group: "Aves basales / Dinosaurio terópodo avialano",
    diet: "Carnívoro insectívoro (Insectos, pequeños lagartos)",
    habitat: "Insular y costero (Archipiélago de lagunas salobres de Solnhofen)",
    length: "0.5 m",
    weight: "0.8 kg",
    scaleVsHuman: "Del tamaño de un cuervo o urraca europea.",
    description: "El fósil de transición más célebre de la paleontología evolutiva. Reveló de manera inequívoca el vínculo directo entre los dinosaurios terópodos y las aves modernas: combinaba dientes afilados, garras en las alas y una larga cola ósea de reptil con plumas de vuelo asimétricas idénticas a las actuales.",
    lat: 48.89,
    lon: 11.00,
    fossilSite: "Calizas litográficas de Solnhofen, Baviera (Alemania)"
  },
  {
    id: "kentrosaurus",
    name: "Kentrosaurus aethiopicus",
    commonName: "Centrosaurio (Lagarto Puntiagudo)",
    image: "assets/species/kentrosaurus.jpg",
    group: "Dinosaurio ornitisquio (Estegosáuridos espinosos)",
    diet: "Herbívoro bajo (Matorrales y helechos)",
    habitat: "Terrestre (Bosques costeros tropicales del este de Gondwana)",
    length: "4.5 m",
    weight: "1.2 toneladas",
    scaleVsHuman: "Menor que Stegosaurus pero con temibles púas pares laterales en hombros y caderas.",
    description: "Estegosáurido africano caracterizado por una transición gradual de pequeñas placas óseas en el cuello a enormes púas gemelas afiladas a lo largo de la espalda, flancos y cola, transformándolo en una fortaleza viviente ante terópodos.",
    lat: -9.85,
    lon: 39.30,
    fossilSite: "Yacimiento de Tendaguru (Tanzania, África Oriental)"
  }
];
data.periods[5].species = jurassic150Species;

// 6. Triassic 200 Ma: Plateosaurus, Herrerasaurus, Eoraptor
const triassic200Species = [
  {
    id: "plateosaurus",
    name: "Plateosaurus trossingensis",
    commonName: "Plateosaurio (Lagarto Plano)",
    image: "assets/species/plateosaurus.jpg",
    group: "Dinosaurio prosaurópodo (Plateosáuridos)",
    diet: "Herbívoro ramoneador (Cícadas, ginkgos y helechos altos)",
    habitat: "Terrestre (Llanuras de inundación áridas de Pangea central)",
    length: "8.0 m",
    weight: "2.5 toneladas",
    scaleVsHuman: "Capaz de alzarse bípedamente para ramonear a más de 4 metros de altura.",
    description: "Uno de los primeros grandes dinosaurios herbívoros de la historia. Caminaba de forma bípeda y poseía manos provistas de un pulgar con garra curvada prensil para acercar ramas a su boca, prefigurando la radiación colosal de los saurópodos jurásicos.",
    lat: 48.07,
    lon: 8.63,
    fossilSite: "Trossingen y Frick, Formación Löwenstein (Alemania / Suiza)"
  },
  {
    id: "herrerasaurus",
    name: "Herrerasaurus ischigualastensis",
    commonName: "Herrerasaurio",
    image: "assets/species/herrerasaurus.jpg",
    group: "Dinosaurio saurisquio basal (Herrerasáuridos)",
    diet: "Carnívoro veloz (Cazador de rincosaurios y cinodontes)",
    habitat: "Terrestre (Valles fluviales semiáridos del suroeste de Pangea)",
    length: "4.5 m",
    weight: "250 kg",
    scaleVsHuman: "Depredador ágil y esbelto con patas traseras largas adaptadas a la carrera veloz.",
    description: "Uno de los dinosaurios carnívoros más primitivos y completos del registro fósil mundial. Presentaba una articulación mandibular móvil que le permitía sujetar presas forcejeantes con sus dientes aserrados curvados hacia atrás.",
    lat: -30.15,
    lon: -67.85,
    fossilSite: "Parque Provincial Ischigualasto, Valle de la Luna, San Juan (Argentina)"
  },
  {
    id: "eoraptor",
    name: "Eoraptor lunensis",
    commonName: "Eoraptor (Ladrón del Amanecer)",
    image: "assets/species/eoraptor.jpg",
    group: "Dinosaurio saurisquio basal",
    diet: "Omnívoro / Carnívoro facultativo",
    habitat: "Terrestre (Valles aluviales de Pangea)",
    length: "1.0 m",
    weight: "10 kg",
    scaleVsHuman: "Del tamaño de un perro pequeño o zorro, muy grácil y veloz.",
    description: "El amanecer de la era de los dinosaurios. Descubierto en 1991 en las áridas rocas triásicas de Ischigualasto, su dentición mixta atestigua el origen común de los linajes carnívoros y herbívoros.",
    lat: -30.10,
    lon: -67.80,
    fossilSite: "Formación Ischigualasto, San Juan (Argentina)"
  }
];
data.periods[6].species = triassic200Species;

// 7. Permian 250 Ma: Dimetrodon (from Mundo Prehistorico), Inostrancevia, Scutosaurus, Edaphosaurus, Eryops, Seymouria
const permian250Species = [
  {
    id: "dimetrodon",
    name: "Dimetrodon limbatus",
    commonName: "Dimetrodon (Dos Medidas de Dientes)",
    image: "assets/species/dimetrodon_mundo.jpg",
    group: "Sinápsido esfenacodóntido (Linaje ancestral de los mamíferos)",
    diet: "Carnívoro (Superdepredador pérmico de anfibios y reptiles)",
    habitat: "Terrestre / Ripícola (Llanuras deltaicas áridas y pantanos)",
    length: "3.5 m",
    weight: "250 kg",
    scaleVsHuman: "Más de 1.8 metros de altura en la cumbre de su vela dorsal membranosa vascularizada.",
    description: "El sinápsido más emblemático del Pérmico. Aunque comúnmente confundido con un dinosaurio, está mucho más estrechamente emparentado con los mamíferos que con los reptiles. Su espectacular vela dorsal sostenida por prolongaciones vertebrales servía como termorregulador solar y reclamo reproductor.",
    lat: 33.60,
    lon: -99.30,
    fossilSite: "Red Beds de Texas y Oklahoma (EE. UU.)"
  },
  {
    id: "inostrancevia",
    name: "Inostrancevia alexandri",
    commonName: "Inostrancevia (Gorgonópsido Gigante)",
    image: "assets/species/inostrancevia.jpg",
    group: "Sinápsido terápsido (Gorgonópsidos)",
    diet: "Carnívoro superdepredador (Especializado en cazar pareiasaurios blindados)",
    habitat: "Terrestre (Llanuras semiáridas aluviales de la Rusia pérmica)",
    length: "3.5 m",
    weight: "300 kg",
    scaleVsHuman: "Del porte de un león o un gran oso, con descomunales caninos de sable de 15 cm.",
    description: "El tigre de dientes de sable del Pérmico tardío. Sus colmillos de sable y su cráneo reforzado estaban adaptados para perforar la dura armadura osteodérmica de herbívoros contemporáneos como Scutosaurus en las costas de Pangea septentrional.",
    lat: 62.80,
    lon: 43.10,
    fossilSite: "Yacimientos del Río Dvina Septentrional, Óblast de Arcángel (Rusia)"
  },
  {
    id: "scutosaurus",
    name: "Scutosaurus karpinskii",
    commonName: "Escutosaurio (Reptil Escudo)",
    image: "assets/species/scutosaurus.jpg",
    group: "Anápsido pararreptil (Pareiasáuridos)",
    diet: "Herbívoro (Vegetación fibrosa baja y helechos pérmicos)",
    habitat: "Terrestre (Planicies aluviales semiáridas)",
    length: "3.0 m",
    weight: "1,200 kg",
    scaleVsHuman: "Cuerpo cilíndrico robusto de patas columnares gruesas como un rinoceronte.",
    description: "Tanque biológico del Pérmico tardío. Todo su cuerpo estaba cubierto de placas óseas dérmicas soldadas y protuberancias en las mejillas, adaptado para procesar enormes cantidades de vegetación dura en su espacioso abdomen fermentador.",
    lat: 61.20,
    lon: 46.50,
    fossilSite: "Sokolki, Río Malaya Severnaya Dvina (Rusia)"
  },
  {
    id: "edaphosaurus",
    name: "Edaphosaurus pogonias",
    commonName: "Edafosaurio",
    image: "assets/species/edaphosaurus.jpg",
    group: "Sinápsido pelicosaurio (Edafosaúridos)",
    diet: "Herbívoro (Equisetos, helechos y plantas ricas en celulosa)",
    habitat: "Húmedo y pantanoso",
    length: "3.2 m",
    weight: "200 kg",
    scaleVsHuman: "Vela con barras transversales óseas perpendiculares semejantes a varillas de antena.",
    description: "Uno de los primeros vertebrados herbívoros terrestres de gran porte. Poseía placas de dientes en el paladar para moler plantas y una vela dorsal con protuberancias transversales únicas.",
    lat: 33.50,
    lon: -99.00,
    fossilSite: "Archer County, Texas (EE. UU.)"
  }
];
data.periods[7].species = permian250Species;

// 8. Cambrian 540 Ma: Anomalocaris (from Mundo Prehistorico), Trilobites (from Mundo Prehistorico), Opabinia, Pikaia, Haikouichthys
const cambrian540Species = [
  {
    id: "anomalocaris",
    name: "Anomalocaris canadensis",
    commonName: "Anomalocaris (Gamba Extraña)",
    image: "assets/species/anomalocaris_mundo.jpg",
    group: "Radiodonto artrópodo basal (Anomalocarídidos)",
    diet: "Carnívoro (Superdepredador ápice de los mares cámbricos)",
    habitat: "Marino bentónico y pelágico de plataforma",
    length: "1.0 m",
    weight: "4.0 kg",
    scaleVsHuman: "El leviatán de su tiempo; en un océano donde la mayoría de los seres medían pocos centímetros.",
    description: "El superdepredador por excelencia de la Explosión Cámbrica. Poseía dos ojos compuestos pedunculados formados por más de 16,000 lentes individuales, dos apéndices frontales articulados espinosos para atrapar presas y una boca circular en forma de rodaja de piña armada con placas concéntricas trituradoras.",
    lat: 51.40,
    lon: -116.50,
    fossilSite: "Burgess Shale, Parque Nacional Yoho (Columbia Británica, Canadá)"
  },
  {
    id: "trilobites",
    name: "Olenoides serratus",
    commonName: "Trilobites Cámbrico",
    image: "assets/species/trilobites_mundo.jpg",
    group: "Artrópodo extinto (Trilobita)",
    diet: "Bentónico detritívoro y carnívoro de fondo",
    habitat: "Marino bentónico (Fondos oceánicos someros cámbricos)",
    length: "10 cm",
    weight: "50 g",
    scaleVsHuman: "Del tamaño de la palma de una mano humana, con exoesqueleto trilobulado calcificado.",
    description: "El artrópodo más exitoso de la era Paleozoica temprana. Con un exoesqueleto articulado de calcita dividido en tres lóbulos longitudinales y ojos de calcita pura con óptica bifocal perfecta, dominó los fondos marinos durante casi 300 millones de años.",
    lat: 51.45,
    lon: -116.48,
    fossilSite: "Burgess Shale (Canadá) y Esquisto de Maotianshan (Chengjiang, China)"
  },
  {
    id: "opabinia",
    name: "Opabinia regalis",
    commonName: "Opabinia (Cinco Ojos)",
    image: "assets/species/opabinia.jpg",
    group: "Artrópodo basal (Opabínidos)",
    diet: "Carnívoro de fondo (Cazador de pequeños gusanos e invertebrados blandos)",
    habitat: "Marino bentónico somero",
    length: "7 cm",
    weight: "20 g",
    scaleVsHuman: "Cuerpo alargado y suave de pocos centímetros con 5 ojos dorsales.",
    description: "Una de las criaturas más asombrosas y desconcertantes de la fauna de Burgess Shale. Dotada de cinco ojos pedunculados con visión panorámica de 360 grados y una trompa frontal flexible extensible rematada en pinzas dentadas con la que atrapaba invertebrados de los sedimentos marinos.",
    lat: 51.41,
    lon: -116.51,
    fossilSite: "Cantera de Walcott, Burgess Shale (Canadá)"
  },
  {
    id: "pikaia",
    name: "Pikaia gracilens",
    commonName: "Pikaia (Ancestro de los Cordados)",
    image: "assets/species/pikaia.jpg",
    group: "Cordado primitivo (Linaje de los vertebrados)",
    diet: "Filtrador bentónico / Suspensívoro",
    habitat: "Marino libre nadador somero",
    length: "5 cm",
    weight: "5 g",
    scaleVsHuman: "Poco mayor que un dedo meñique humano; el tatarabuelo de todos los animales con columna vertebral.",
    description: "Especie crucial para entender nuestros propios orígenes evolutivos. Este animal vermiforme dotado de una notocorda dorsal precursora de la columna vertebral y miómeros musculares en forma de zig-zag es el representante más representativo de los primeros cordados.",
    lat: 51.42,
    lon: -116.49,
    fossilSite: "Cresta de los Fósiles, Burgess Shale (Columbia Británica, Canadá)"
  }
];
data.periods[12].species = cambrian540Species;

// 9. Ediacaran 600 Ma: Spriggina with real JPG photo
if (data.periods[13] && data.periods[13].species) {
  const spriggina = data.periods[13].species.find(s => s.id === 'spriggina');
  if (spriggina) {
    spriggina.image = "assets/species/spriggina.jpg";
  }
}

// Save updated file
fs.writeFileSync('public/data/fauna_flora.json', JSON.stringify(data, null, 2), 'utf8');
console.log('Successfully updated fauna_flora.json with real photos and full megafauna catalog!');
